"use strict";
// Urban Runner v2 - pseudo-3D behind-view lane runner
const cv=document.getElementById('cv'),ctx=cv.getContext('2d');
let W=0,H=0,DPR=1,HORIZON=0,BASE=0,ROADW=0;
function resize(){const r=document.getElementById('stage').getBoundingClientRect();DPR=Math.min(window.devicePixelRatio||1,2);W=r.width;H=r.height;cv.width=W*DPR;cv.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0);HORIZON=H*0.40;BASE=H*0.94;ROADW=W*0.30;}
window.addEventListener('resize',resize);resize();
function scaleOf(z){return 1/(1+z*2.6);}
function project(worldX,z){const s=scaleOf(z);return{x:W/2+worldX*ROADW*s,y:HORIZON+(BASE-HORIZON)*s,s};}
const Z_PLAYER=0.16,Z_SPAWN=6.2;
const SAVE_KEY='urbanRunner_v2';
const baseOwned=()=>({hero:true,athlete:false,ninja:false,robo:false,captain:false,navigator:false,dragon:false});
const defaults={coins:105432,gems:1450,best:105432,selected:'hero',owned:baseOwned(),skills:{magnet:1,shield:1,boost:0,multiplier:0},sound:true,music:true,vibe:false};
let S=load();
function load(){try{const d=JSON.parse(localStorage.getItem(SAVE_KEY));if(d)return Object.assign({},JSON.parse(JSON.stringify(defaults)),d);}catch(e){}return JSON.parse(JSON.stringify(defaults));}
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(S));}catch(e){}}
const CHARS={hero:{name:'Urban Runner',cost:{c:0},pal:{hair:'#7a4a26',band:'#3555b0',scarf:'#d43a2a',shirt:'#e3e8ef',pants:'#26407a',shoe:'#5a3a22',skin:'#e8b48c'}},athlete:{name:'Girl Athlete',cost:{c:30000},pal:{hair:'#6b3f22',band:'#22c3c9',scarf:'#a855c9',shirt:'#a855c9',pants:'#22c3c9',shoe:'#8a4ad0',skin:'#f0c9a8'},ponytail:true},ninja:{name:'Shadow Ninja',cost:{c:45000},pal:{hair:'#141824',band:'#e08a2a',scarf:'#e08a2a',shirt:'#2a3550',pants:'#1c2436',shoe:'#141824',skin:'#f0c9a8'},mask:true},robo:{name:'Robo-Runner',cost:{c:55000},pal:{hair:'#c9cdd6',band:'#f7c948',scarf:'#f7c948',shirt:'#e0453a',pants:'#c9cdd6',shoe:'#e0453a',skin:'#dfe4ea'},robo:true},captain:{name:'Sea Captain',cost:{c:70000},pal:{hair:'#6b4a2a',band:'#1c2a3a',scarf:'#e0b84a',shirt:'#26507a',pants:'#1c2a3a',shoe:'#3a2a1a',skin:'#e8b48c'},hat:true},navigator:{name:'Star Navigator',cost:{g:200},pal:{hair:'#dfe4ea',band:'#5aa0e0',scarf:'#5aa0e0',shirt:'#eef2f7',pants:'#c9cdd6',shoe:'#5aa0e0',skin:'#e8b48c'},helmet:true},dragon:{name:'Dragon Knight',cost:{g:250},pal:{hair:'#9aa0aa',band:'#e0453a',scarf:'#e0453a',shirt:'#9aa0aa',pants:'#6b7079',shoe:'#4a4e56',skin:'#e8b48c'},helm:true}};
const SKILL_DEFS={magnet:{name:'Coin Magnet',desc:'Pulls nearby coins toward you',max:5,base:8000},shield:{name:'Shield',desc:'Longer protection duration',max:5,base:9000},boost:{name:'Rocket Boost',desc:'Fly & smash everything',max:5,base:12000},multiplier:{name:'2X Score',desc:'Longer double-points window',max:5,base:14000}};
function rr(g,x,y,w,h,r){g.beginPath();g.moveTo(x+r,y);g.arcTo(x+w,y,x+w,y+h,r);g.arcTo(x+w,y+h,x,y+h,r);g.arcTo(x,y+h,x,y,r);g.arcTo(x,y,x+w,y,r);g.closePath();}
function drawRunner(g,cx,cy,sc,phase,pose,id){const c=CHARS[id]||CHARS.hero,p=c.pal;g.save();g.translate(cx,cy);g.scale(sc,sc);if(pose===2){g.scale(1.15,0.55);g.translate(0,44);}const run=pose===0,sw=run?Math.sin(phase)*11:6,aw=run?Math.sin(phase+Math.PI)*9:-4;g.lineCap='round';g.strokeStyle=p.pants;g.lineWidth=9;g.beginPath();g.moveTo(-5,-34);g.lineTo(-5+sw,-4);g.stroke();g.beginPath();g.moveTo(5,-34);g.lineTo(5-sw,-4);g.stroke();g.fillStyle=p.shoe;g.beginPath();g.ellipse(-5+sw,-2,6,4.5,0,0,7);g.fill();g.beginPath();g.ellipse(5-sw,-2,6,4.5,0,0,7);g.fill();g.fillStyle=p.shirt;rr(g,-13,-62,26,32,9);g.fill();g.fillStyle='rgba(0,0,0,0.08)';rr(g,-3,-60,6,28,3);g.fill();if(!c.mask){g.fillStyle=p.scarf;g.beginPath();g.moveTo(9,-58);g.quadraticCurveTo(24+sw,-54,20,-44);g.quadraticCurveTo(14,-48,9,-50);g.fill();}g.strokeStyle=p.shirt;g.lineWidth=7;g.beginPath();g.moveTo(-11,-56);g.lineTo(-15+aw,-40);g.stroke();g.beginPath();g.moveTo(11,-56);g.lineTo(15-aw,-40);g.stroke();g.fillStyle=p.skin;g.beginPath();g.arc(-15+aw,-39,3.6,0,7);g.fill();g.beginPath();g.arc(15-aw,-39,3.6,0,7);g.fill();g.fillStyle=p.skin;g.beginPath();g.arc(0,-76,13,0,7);g.fill();g.fillStyle=p.hair;g.beginPath();g.arc(0,-78,13,0,7);g.fill();if(c.robo){g.fillStyle='#e0453a';g.beginPath();g.arc(0,-76,13.5,0,7);g.fill();g.fillStyle=p.band;g.fillRect(-13,-73,26,4);}else if(c.hat){g.fillStyle='#1c2a3a';g.beginPath();g.ellipse(0,-84,17,6,0,0,7);g.fill();g.beginPath();g.arc(0,-82,11,Math.PI,0);g.fill();}else if(c.helmet){g.fillStyle='#eef2f7';g.beginPath();g.arc(0,-77,14,0,7);g.fill();g.fillStyle=p.band;g.fillRect(-14,-79,28,4);}else if(c.helm){g.fillStyle='#c9cdd6';g.beginPath();g.arc(0,-77,14,0,7);g.fill();g.fillStyle=p.band;g.beginPath();g.moveTo(-2,-92);g.lineTo(2,-92);g.lineTo(0,-82);g.fill();}else if(c.mask){g.fillStyle=p.shirt;g.beginPath();g.arc(0,-76,13.5,0,7);g.fill();g.fillStyle=p.band;g.fillRect(-13.5,-74,27,5);}else{g.fillStyle=p.band;rr(g,-13,-80,26,6,3);g.fill();}if(c.ponytail){g.fillStyle=p.hair;g.beginPath();g.ellipse(0,-70,7,13,0,0,7);g.fill();}g.restore();}
function drawPortrait(g,cx,cy,sc,phase,id){const c=CHARS[id]||CHARS.hero,p=c.pal;g.save();g.translate(cx,cy);g.scale(sc,sc);const sw=Math.sin(phase)*10;g.lineCap='round';g.strokeStyle=p.pants;g.lineWidth=8;g.beginPath();g.moveTo(0,-32);g.lineTo(-6+sw,-2);g.stroke();g.beginPath();g.moveTo(0,-32);g.lineTo(6-sw,-2);g.stroke();g.fillStyle=p.shoe;g.beginPath();g.ellipse(-6+sw,-1,7,4.5,0,0,7);g.fill();g.beginPath();g.ellipse(6-sw,-1,7,4.5,0,0,7);g.fill();g.fillStyle=p.shirt;rr(g,-12,-60,24,30,9);g.fill();if(!c.mask){g.fillStyle=p.scarf;rr(g,-12,-52,24,7,3);g.fill();}g.strokeStyle=p.shirt;g.lineWidth=6;g.beginPath();g.moveTo(-9,-54);g.lineTo(-15-sw*.4,-40);g.stroke();g.beginPath();g.moveTo(9,-54);g.lineTo(15+sw*.4,-42);g.stroke();g.fillStyle=p.skin;g.beginPath();g.arc(0,-72,13,0,7);g.fill();g.save();g.translate(0,-72);if(c.mask){g.fillStyle=p.shirt;g.beginPath();g.arc(0,0,13.5,-.2,Math.PI+.2);g.fill();rr(g,-13.5,-2,27,7,2);g.fill();g.fillStyle='#fff';g.fillRect(-6,2,4,2.5);g.fillRect(3,2,4,2.5);}else if(c.robo){g.fillStyle=p.shirt;g.beginPath();g.arc(0,0,13.5,0,7);g.fill();g.fillStyle='#2ad4d4';g.beginPath();g.arc(3,-1,6,0,7);g.fill();}else if(c.hat){g.fillStyle='#1c2a3a';g.beginPath();g.ellipse(0,-9,17,7,0,0,7);g.fill();g.beginPath();g.arc(0,-11,10,Math.PI,0);g.fill();g.fillStyle=p.hair;rr(g,-9,2,18,10,5);g.fill();g.fillStyle='#1c2a3a';g.fillRect(-7,-2,14,3);}else if(c.helmet){g.fillStyle='#eef2f7';g.beginPath();g.arc(0,-1,14,0,7);g.fill();g.fillStyle='#2a3550';g.beginPath();g.arc(1,0,9,0,7);g.fill();}else if(c.helm){g.fillStyle='#c9cdd6';g.beginPath();g.arc(0,-2,14,Math.PI,0);g.fill();rr(g,-13,-3,26,10,3);g.fill();g.fillStyle=p.band;g.beginPath();g.moveTo(-2,-16);g.lineTo(2,-16);g.lineTo(0,-24);g.fill();g.fillStyle='#2a2a2a';g.fillRect(-8,-1,16,4);}else if(c.ponytail){g.fillStyle=p.hair;g.beginPath();g.arc(0,-4,13,Math.PI,0);g.fill();g.beginPath();g.ellipse(11,-4,5,10,0,0,7);g.fill();g.fillStyle=p.band;rr(g,-13,-8,26,4,2);g.fill();g.fillStyle='#3a2a1a';g.beginPath();g.arc(3,0,1.6,0,7);g.fill();}else{g.fillStyle=p.hair;g.beginPath();g.arc(0,-3,13,Math.PI,0);g.fill();g.fillRect(-13,-3,26,5);g.fillStyle=p.band;rr(g,-13,-6,26,5,2);g.fill();g.fillStyle='#3a2a1a';g.beginPath();g.arc(3,0,1.6,0,7);g.fill();}g.restore();g.restore();}
let scroll=0;const buildings=[];
function seedWorld(){buildings.length=0;for(let i=0;i<26;i++){const side=i%2?1:-1;buildings.push({side,z:(i>>1)*0.9+Math.random()*0.4,h:0.9+Math.random()*1.1,hue:15+Math.random()*40});}}
seedWorld();
function drawSky(){const sky=ctx.createLinearGradient(0,0,0,HORIZON);sky.addColorStop(0,'#5b6bb5');sky.addColorStop(.55,'#c98db0');sky.addColorStop(1,'#ffcf87');ctx.fillStyle=sky;ctx.fillRect(0,0,W,HORIZON+2);ctx.fillStyle='rgba(255,240,190,0.85)';ctx.beginPath();ctx.arc(W/2,HORIZON-6,46,0,7);ctx.fill();ctx.fillStyle='rgba(255,225,160,0.35)';ctx.beginPath();ctx.arc(W/2,HORIZON-6,80,0,7);ctx.fill();ctx.fillStyle='rgba(70,60,110,0.55)';let x=0;while(x<W){const bw=18+((x*7)%40),bh=20+((x*13)%60);ctx.fillRect(x,HORIZON-bh,bw,bh);x+=bw+6;}}
function drawGround(){ctx.fillStyle='#7d5a86';ctx.fillRect(0,HORIZON,W,H-HORIZON);const nearL=project(-1.55,0),nearR=project(1.55,0),farL=project(-1.55,Z_SPAWN),farR=project(1.55,Z_SPAWN);ctx.fillStyle='#4a4750';ctx.beginPath();ctx.moveTo(farL.x,farL.y);ctx.lineTo(farR.x,farR.y);ctx.lineTo(nearR.x,nearR.y);ctx.lineTo(nearL.x,nearL.y);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,0.16)';ctx.lineWidth=2;for(const lx of[-0.5,0.5]){const a=project(lx,0),b=project(lx,Z_SPAWN);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}ctx.fillStyle='rgba(255,255,255,0.6)';for(let i=0;i<14;i++){const z=((i*0.5-(scroll%0.5))+0.001);if(z<0.02)continue;const a=project(0,z),b=project(0,z+0.22);const w=6*a.s+1;ctx.beginPath();ctx.moveTo(a.x-w,a.y);ctx.lineTo(a.x+w,a.y);ctx.lineTo(b.x+w*0.7,b.y);ctx.lineTo(b.x-w*0.7,b.y);ctx.closePath();ctx.fill();}const sorted=buildings.slice().sort((a,b)=>b.z-a.z);for(const bd of sorted){if(bd.z<0.02)continue;const baseP=project(bd.side*2.15,bd.z);const w=W*0.5*baseP.s,h=(BASE-HORIZON)*bd.h*baseP.s;const top=baseP.y-h;ctx.fillStyle='hsl('+bd.hue+',32%,'+(38+bd.z*3)+'%)';const bx=bd.side<0?baseP.x-w:baseP.x;ctx.fillRect(bx,top,w,h);ctx.fillStyle='rgba(0,0,0,0.18)';ctx.fillRect(bd.side<0?bx+w-w*0.22:bx,top,w*0.22,h);ctx.fillStyle='rgba(255,225,150,0.7)';const cols=Math.max(2,Math.floor(w/(14*baseP.s+6)));for(let r=0;r<Math.floor(h/(20*baseP.s+6));r++)for(let cc=0;cc<cols;cc++){if((r+cc)%3===0)continue;ctx.fillRect(bx+6+cc*(w/cols),top+8+r*(20*baseP.s+6),w/cols*0.5,10*baseP.s+3);}}}
const OB_BLOCK=['crate','cone','barrel','fire','spikes'],OB_HIGH='barrier';
const PW_KINDS=['magnet','shield','rocket','lightning','multiplier'];
const player={lane:1,curLane:1,y:0,vy:0,onGround:true,duck:0,phase:0};
let game=null,mode='menu';
function newGame(){return{speed:2.0,dist:0,score:0,coins:0,lives:3,obs:[],coins_a:[],gems:[],pw:[],spawnZ:Z_SPAWN,coinZ:Z_SPAWN,pwZ:Z_SPAWN+3,magnet:0,shield:0,rocket:0,mult:0,boost:0,invuln:0,over:false};}
function startRun(){game=newGame();player.lane=1;player.curLane=1;player.y=0;player.vy=0;player.onGround=true;player.duck=0;player.phase=0;scroll=0;particles.length=0;seedWorld();game.magnetDur=2.5+S.skills.magnet*0.9;game.shieldDur=3+S.skills.shield;game.rocketDur=2.5+S.skills.boost*0.7;game.multDur=4+S.skills.multiplier*1.2;showScreen('game');renderHearts(3);document.getElementById('boostbar').innerHTML='';document.getElementById('hint').style.opacity='0.95';hintHidden=false;mode='countdown';runCountdown();}
function runCountdown(){const el=document.getElementById('countdown'),sp=el.querySelector('span');el.classList.remove('hidden');let n=3;sp.textContent=n;pop(sp);const iv=setInterval(()=>{n--;if(n>0){sp.textContent=n;pop(sp);}else if(n===0){sp.textContent='GO!';pop(sp);}else{clearInterval(iv);el.classList.add('hidden');mode='play';}},700);}
function pop(el){el.style.transition='none';el.style.transform='scale(1.4)';el.style.opacity='.2';requestAnimationFrame(()=>{el.style.transition='transform .5s cubic-bezier(.16,1,.3,1),opacity .5s';el.style.transform='scale(1)';el.style.opacity='1';});}
function moveLane(d){if(mode!=='play')return;player.lane=Math.max(0,Math.min(2,player.lane+d));beep(440,0.05);}
function jump(){if(mode!=='play')return;if(player.onGround||game.rocket>0){player.vy=game.rocket>0?-3.0:-6.2;player.onGround=false;player.duck=0;beep(560,0.06);}}
function slide(){if(mode!=='play')return;if(player.onGround)player.duck=0.6;}
function update(dt){if(mode!=='play'||game.over)return;const g=game;g.speed=2.0+Math.min(g.dist*0.0015,2.6);const boosting=g.rocket>0||g.boost>0;const spd=g.speed*(boosting?1.7:1);const move=spd*dt;g.dist+=move*6;scroll+=move;const mult=g.mult>0?2:1;g.score+=move*22*mult;player.curLane+=(player.lane-player.curLane)*Math.min(1,dt*11);player.phase+=dt*(11+spd*2.2);if(g.rocket>0){player.y+=(-140-player.y)*Math.min(1,dt*5);player.vy=0;player.onGround=false;}else{player.vy+=22*dt;player.y+=player.vy*dt*60;if(player.y>=0){player.y=0;player.vy=0;player.onGround=true;}}if(player.duck>0)player.duck=Math.max(0,player.duck-dt);['magnet','shield','rocket','mult','boost','invuln'].forEach(k=>{if(g[k]>0)g[k]-=dt;});g.spawnZ-=move;if(g.spawnZ<=0){spawnObstacle(g);g.spawnZ=Math.max(1.1,2.4-g.dist*0.00035)+Math.random()*0.8;}g.coinZ-=move;if(g.coinZ<=0){spawnCoins(g);g.coinZ=1.6+Math.random()*1.8;}g.pwZ-=move;if(g.pwZ<=0){spawnPowerup(g);g.pwZ=11+Math.random()*8;}for(const o of g.obs)o.z-=move;for(const c of g.coins_a)c.z-=move;for(const gm of g.gems)gm.z-=move;for(const p of g.pw)p.z-=move;g.obs=g.obs.filter(o=>o.z>-0.5);g.coins_a=g.coins_a.filter(c=>!c.dead&&c.z>-0.5);g.gems=g.gems.filter(x=>!x.dead&&x.z>-0.5);g.pw=g.pw.filter(p=>!p.dead&&p.z>-0.5);if(g.magnet>0){for(const c of g.coins_a)if(c.z<1.4)c.lane+=(player.curLane-1-c.lane)*Math.min(1,dt*6);for(const gm of g.gems)if(gm.z<1.4)gm.lane+=(player.curLane-1-gm.lane)*Math.min(1,dt*6);}const pl=player.curLane-1;const collideZ=z=>z<Z_PLAYER+0.14&&z>Z_PLAYER-0.14;const sameLane=lx=>Math.abs(lx-pl)<0.45;for(const c of g.coins_a){if(!c.dead&&collideZ(c.z)&&sameLane(c.lane)&&player.y>-90){c.dead=true;g.coins++;g.score+=10*mult;burst(project(c.lane,c.z),'#f7c948',6);beep(880,0.03);}}for(const gm of g.gems){if(!gm.dead&&collideZ(gm.z)&&sameLane(gm.lane)&&player.y>-90){gm.dead=true;S.gems++;g.score+=50*mult;burst(project(gm.lane,gm.z),'#e0453a',9);beep(1100,0.05);}}for(const p of g.pw){if(!p.dead&&collideZ(p.z)&&sameLane(p.lane)){p.dead=true;applyPW(p.kind,g);burst(project(p.lane,p.z),'#ffd23f',12);beep(700,0.12);}}if(g.invuln<=0&&g.rocket<=0){for(const o of g.obs){if(o.hit||!collideZ(o.z)||!sameLane(o.lane))continue;let safe=false;if(o.high){if(player.duck>0)safe=true;}else{if(player.y<-40)safe=true;}if(!safe){if(g.shield>0){g.shield=0;g.invuln=1;o.hit=true;burst(project(o.lane,o.z),'#5aa0e0',14);toast('Shield broke!');beep(300,0.14);}else{o.hit=true;hitPlayer(g);}}else o.hit=true;}}for(const pt of particles){pt.vy+=900*dt;pt.x+=pt.vx*dt;pt.y+=pt.vy*dt;pt.life-=dt;}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);document.getElementById('g-score').textContent=Math.floor(g.score).toLocaleString();document.getElementById('g-coins').textContent=(S.coins+g.coins).toLocaleString();document.getElementById('distbox').textContent=Math.floor(g.dist)+' m';updateBoostBar();}
function hitPlayer(g){g.lives--;g.invuln=1.4;renderHearts(g.lives);burst({x:W/2+(player.curLane-1)*ROADW*scaleOf(Z_PLAYER),y:BASE-60,s:1},'#e0453a',14);beep(200,0.2);vibrate(120);if(g.lives<=0)endRun();}
function spawnObstacle(g){const high=g.dist>160&&Math.random()<0.32;const lane=Math.floor(Math.random()*3);const type=high?OB_HIGH:OB_BLOCK[Math.floor(Math.random()*OB_BLOCK.length)];g.obs.push({type,high,lane,z:Z_SPAWN,hit:false});if(!high&&Math.random()<0.25){let l2=(lane+1+Math.floor(Math.random()*2))%3;if(l2!==lane)g.obs.push({type:OB_BLOCK[Math.floor(Math.random()*OB_BLOCK.length)],high:false,lane:l2,z:Z_SPAWN,hit:false});}}
function spawnCoins(g){const lane=Math.floor(Math.random()*3),n=4+Math.floor(Math.random()*4);for(let i=0;i<n;i++)g.coins_a.push({lane,z:Z_SPAWN+i*0.55,ph:Math.random()*6,dead:false});if(Math.random()<0.25)g.gems.push({lane,z:Z_SPAWN+n*0.55,ph:Math.random()*6,dead:false});}
function spawnPowerup(g){g.pw.push({kind:PW_KINDS[Math.floor(Math.random()*PW_KINDS.length)],lane:Math.floor(Math.random()*3),z:Z_SPAWN,dead:false});}
function applyPW(k,g){if(k==='magnet'){g.magnet=g.magnetDur;toast('Magnet!');}else if(k==='shield'){g.shield=g.shieldDur;toast('Shield up!');}else if(k==='rocket'){g.rocket=g.rocketDur;toast('Blast off!');}else if(k==='lightning'){g.boost=2.5;toast('Speed boost!');}else{g.mult=g.multDur;toast('2X Score!');}}
function drawObstacle(o){const p=project(o.lane,o.z);if(p.s<0.02)return;const s=p.s*84;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='rgba(0,0,0,0.22)';ctx.beginPath();ctx.ellipse(0,2,s*0.55,s*0.14,0,0,7);ctx.fill();if(o.high){ctx.fillStyle='#d43a2a';rr(ctx,-s*0.75,-s*2.0,s*1.5,s*0.42,4);ctx.fill();ctx.save();rr(ctx,-s*0.75,-s*2.0,s*1.5,s*0.42,4);ctx.clip();for(let i=0;i<6;i++){ctx.fillStyle=i%2?'#fff':'#d43a2a';ctx.fillRect(-s*0.75+i*s*0.28,-s*2.0,s*0.28,s*0.42);}ctx.restore();ctx.strokeStyle='#b8bcc4';ctx.lineWidth=Math.max(2,s*0.06);ctx.beginPath();ctx.moveTo(-s*0.55,-s*1.6);ctx.lineTo(-s*0.55,0);ctx.moveTo(s*0.55,-s*1.6);ctx.lineTo(s*0.55,0);ctx.stroke();}else if(o.type==='crate'){ctx.fillStyle='#9c6b3a';rr(ctx,-s*0.5,-s,s,s,4);ctx.fill();ctx.strokeStyle='#6e4a26';ctx.lineWidth=Math.max(2,s*0.05);ctx.strokeRect(-s*0.5,-s,s,s);ctx.beginPath();ctx.moveTo(-s*0.5,-s);ctx.lineTo(s*0.5,0);ctx.moveTo(s*0.5,-s);ctx.lineTo(-s*0.5,0);ctx.stroke();}else if(o.type==='cone'){ctx.fillStyle='#e58a2a';ctx.beginPath();ctx.moveTo(0,-s);ctx.lineTo(s*0.42,0);ctx.lineTo(-s*0.42,0);ctx.fill();ctx.fillStyle='#f4f4f4';rr(ctx,-s*0.3,-s*0.55,s*0.6,s*0.16,2);ctx.fill();ctx.fillStyle='#c96a1a';rr(ctx,-s*0.55,-s*0.14,s*1.1,s*0.14,2);ctx.fill();}else if(o.type==='barrel'){ctx.fillStyle='#8a5a2e';rr(ctx,-s*0.4,-s,s*0.8,s,10);ctx.fill();ctx.strokeStyle='#5c3a1c';ctx.lineWidth=Math.max(2,s*0.05);ctx.beginPath();ctx.moveTo(-s*0.4,-s*0.66);ctx.lineTo(s*0.4,-s*0.66);ctx.moveTo(-s*0.4,-s*0.33);ctx.lineTo(s*0.4,-s*0.33);ctx.stroke();}else if(o.type==='fire'){const t=performance.now()/120;ctx.fillStyle='#5c3a1c';rr(ctx,-s*0.5,-s*0.16,s,s*0.16,3);ctx.fill();for(let i=-1;i<=1;i++){const fh=s*(0.8+0.15*Math.sin(t+i));ctx.fillStyle=i===0?'#ffd23f':'#f4732a';ctx.beginPath();ctx.moveTo(i*s*0.22,-s*0.12);ctx.quadraticCurveTo(i*s*0.22-s*0.12,-fh*0.6,i*s*0.22,-fh);ctx.quadraticCurveTo(i*s*0.22+s*0.12,-fh*0.6,i*s*0.22,-s*0.12);ctx.fill();}}else if(o.type==='spikes'){ctx.fillStyle='#6e4a26';rr(ctx,-s*0.55,-s*0.2,s*1.1,s*0.2,3);ctx.fill();ctx.fillStyle='#b8bcc4';for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(i*s*0.22,-s*0.2);ctx.lineTo(i*s*0.22+s*0.11,-s*0.7);ctx.lineTo(i*s*0.22+s*0.22,-s*0.2);ctx.fill();}}ctx.restore();}
function drawCoinEnt(c){const p=project(c.lane,c.z);if(p.s<0.02)return;const r=p.s*22;const sq=Math.abs(Math.cos(performance.now()/200+c.ph));ctx.save();ctx.translate(p.x,p.y-r*1.4);ctx.scale(sq*0.85+0.15,1);ctx.fillStyle='#e9a324';ctx.beginPath();ctx.arc(0,0,r,0,7);ctx.fill();ctx.fillStyle='#f7c948';ctx.beginPath();ctx.arc(0,0,r*0.72,0,7);ctx.fill();ctx.fillStyle='#c98a1f';const q=r*0.5;ctx.beginPath();ctx.moveTo(-q,q*0.5);ctx.lineTo(-q,-q*0.2);ctx.lineTo(-q*0.4,q*0.2);ctx.lineTo(0,-q*0.5);ctx.lineTo(q*0.4,q*0.2);ctx.lineTo(q,-q*0.2);ctx.lineTo(q,q*0.5);ctx.fill();ctx.restore();}
function drawGemEnt(gm){const p=project(gm.lane,gm.z);if(p.s<0.02)return;const r=p.s*24;ctx.save();ctx.translate(p.x,p.y-r*1.4);ctx.rotate(Math.sin(performance.now()/400+gm.ph)*0.14);ctx.fillStyle='#e0453a';ctx.beginPath();ctx.moveTo(0,r);ctx.lineTo(-r,-r*0.2);ctx.lineTo(-r*0.5,-r);ctx.lineTo(r*0.5,-r);ctx.lineTo(r,-r*0.2);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(255,255,255,0.5)';ctx.beginPath();ctx.moveTo(0,r*0.2);ctx.lineTo(-r*0.5,-r);ctx.lineTo(r*0.5,-r);ctx.closePath();ctx.fill();ctx.restore();}
function drawPWEnt(p0){const p=project(p0.lane,p0.z);if(p.s<0.02)return;const r=p.s*30;ctx.save();ctx.translate(p.x,p.y-r*1.5);const pulse=1+0.08*Math.sin(performance.now()/200);ctx.scale(pulse,pulse);ctx.fillStyle='rgba(255,220,120,0.35)';ctx.beginPath();ctx.arc(0,0,r*1.25,0,7);ctx.fill();const grd=ctx.createRadialGradient(-r*0.3,-r*0.3,2,0,0,r);grd.addColorStop(0,'#4a6ad0');grd.addColorStop(1,'#243a8a');ctx.fillStyle=grd;ctx.beginPath();ctx.arc(0,0,r,0,7);ctx.fill();ctx.strokeStyle='#f7c948';ctx.lineWidth=Math.max(2,r*0.1);ctx.stroke();const s=r;if(p0.kind==='magnet'){ctx.strokeStyle='#e0453a';ctx.lineWidth=r*0.22;ctx.beginPath();ctx.arc(0,-2,s*0.5,Math.PI,0);ctx.stroke();ctx.fillStyle='#e0453a';ctx.fillRect(-s*0.5-r*0.1,-2,r*0.2,s*0.4);ctx.fillRect(s*0.5-r*0.1,-2,r*0.2,s*0.4);}else if(p0.kind==='shield'){ctx.fillStyle='#5aa0e0';ctx.beginPath();ctx.moveTo(0,-s*0.6);ctx.lineTo(s*0.5,-s*0.3);ctx.lineTo(s*0.4,s*0.5);ctx.lineTo(0,s*0.7);ctx.lineTo(-s*0.4,s*0.5);ctx.lineTo(-s*0.5,-s*0.3);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';starPath(ctx,0,0,5,s*0.28,s*0.13);ctx.fill();}else if(p0.kind==='rocket'){ctx.save();ctx.rotate(-0.6);ctx.fillStyle='#e0453a';rr(ctx,-s*0.18,-s*0.5,s*0.36,s*0.8,s*0.18);ctx.fill();ctx.fillStyle='#f7c948';ctx.beginPath();ctx.moveTo(0,-s*0.6);ctx.lineTo(s*0.18,-s*0.3);ctx.lineTo(-s*0.18,-s*0.3);ctx.fill();ctx.fillStyle='#ff8a2a';ctx.beginPath();ctx.moveTo(-s*0.15,s*0.3);ctx.lineTo(0,s*0.7);ctx.lineTo(s*0.15,s*0.3);ctx.fill();ctx.restore();}else if(p0.kind==='lightning'){ctx.fillStyle='#ffd23f';ctx.beginPath();ctx.moveTo(s*0.1,-s*0.6);ctx.lineTo(-s*0.3,s*0.1);ctx.lineTo(0,s*0.1);ctx.lineTo(-s*0.1,s*0.6);ctx.lineTo(s*0.35,-s*0.1);ctx.lineTo(0,-s*0.1);ctx.closePath();ctx.fill();}else{ctx.fillStyle='#ffd23f';ctx.font='bold '+(s*0.9)+'px Fredoka, sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('2×',0,1);}ctx.restore();}
function starPath(g,cx,cy,n,ro,ri){g.beginPath();for(let i=0;i<n*2;i++){const a=Math.PI/n*i-Math.PI/2,r=i%2?ri:ro;g.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);}g.closePath();}
const particles=[];
function burst(p,color,n){for(let i=0;i<n;i++)particles.push({x:p.x,y:p.y,vx:(Math.random()-0.5)*260,vy:-Math.random()*300-60,life:0.6,color,r:2+Math.random()*3});}
function render(){drawSky();drawGround();if(mode==='play'||mode==='countdown'||mode==='pause'){const g=game;const items=[];for(const o of g.obs)items.push({z:o.z,kind:'ob',e:o});for(const c of g.coins_a)if(!c.dead)items.push({z:c.z,kind:'coin',e:c});for(const gm of g.gems)if(!gm.dead)items.push({z:gm.z,kind:'gem',e:gm});for(const p of g.pw)if(!p.dead)items.push({z:p.z,kind:'pw',e:p});items.sort((a,b)=>b.z-a.z);const pz=Z_PLAYER;for(const it of items)if(it.z>=pz)drawItem(it);drawPlayer(g);for(const it of items)if(it.z<pz)drawItem(it);for(const pt of particles){ctx.globalAlpha=Math.max(0,pt.life/0.6);ctx.fillStyle=pt.color;ctx.beginPath();ctx.arc(pt.x,pt.y,pt.r,0,7);ctx.fill();}ctx.globalAlpha=1;}}
function drawItem(it){if(it.kind==='ob')drawObstacle(it.e);else if(it.kind==='coin')drawCoinEnt(it.e);else if(it.kind==='gem')drawGemEnt(it.e);else drawPWEnt(it.e);}
function drawPlayer(g){const p=project(player.curLane-1,Z_PLAYER);const sc=p.s*2.05;const feetY=p.y+player.y;ctx.fillStyle='rgba(0,0,0,0.25)';ctx.beginPath();ctx.ellipse(p.x,p.y+4,34*p.s*2,10*p.s*2,0,0,7);ctx.fill();if(g.rocket>0){ctx.save();ctx.translate(p.x,feetY-8);ctx.fillStyle='#ff8a2a';for(let i=0;i<3;i++){ctx.globalAlpha=0.8-i*0.2;ctx.beginPath();ctx.ellipse(0,14+i*10,10-i*2,16+i*6,0,0,7);ctx.fill();}ctx.globalAlpha=1;ctx.restore();}if(g.shield>0){ctx.save();ctx.strokeStyle='rgba(90,160,224,'+(0.5+0.3*Math.sin(performance.now()/120))+')';ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.x,feetY-64*sc/2,58*p.s*2,0,7);ctx.stroke();ctx.restore();}if(g.mult>0){ctx.save();ctx.fillStyle='rgba(255,210,63,0.14)';ctx.beginPath();ctx.arc(p.x,feetY-64*sc/2,64*p.s*2,0,7);ctx.fill();ctx.restore();}const pose=player.duck>0?2:(player.onGround?0:1);const blink=g.invuln>0&&Math.floor(performance.now()/80)%2===0;if(!blink)drawRunner(ctx,p.x,feetY,sc,player.phase,pose,S.selected);}
let last=performance.now();
function loop(now){let dt=(now-last)/1000;last=now;if(dt>0.05)dt=0.05;update(dt);render();requestAnimationFrame(loop);}
requestAnimationFrame(loop);
function endRun(){game.over=true;mode='over';S.coins+=game.coins;const fin=Math.floor(game.score);const best=fin>S.best;if(best)S.best=fin;save();document.getElementById('go-score').textContent=fin.toLocaleString();document.getElementById('go-coins').textContent=game.coins.toLocaleString();document.getElementById('go-best').textContent=S.best.toLocaleString();document.getElementById('newbest').classList.toggle('hidden',!best);setTimeout(()=>showScreen('gameover'),650);}
function renderHearts(n){const el=document.getElementById('hearts');el.innerHTML='';for(let i=0;i<3;i++)el.insertAdjacentHTML('beforeend','<svg class="'+(i>=n?'lost':'')+'" viewBox="0 0 24 24"><path d="M12 21C5 15.5 3 12 3 8.5A4.5 4.5 0 0112 6a4.5 4.5 0 019 2.5C21 12 19 15.5 12 21z" fill="#e0453a" stroke="#a12a20" stroke-width="1.2"/></svg>');}
function updateBoostBar(){const g=game,bar=document.getElementById('boostbar');const A=[g.magnet>0&&{t:g.magnet,m:g.magnetDur,c:'#e0453a',k:'magnet'},g.shield>0&&{t:g.shield,m:g.shieldDur,c:'#5aa0e0',k:'shield'},g.rocket>0&&{t:g.rocket,m:g.rocketDur,c:'#f7c948',k:'rocket'},g.mult>0&&{t:g.mult,m:g.multDur,c:'#ffd23f',k:'2x'},g.boost>0&&{t:g.boost,m:2.5,c:'#ffd23f',k:'bolt'}].filter(Boolean);bar.innerHTML=A.map(a=>{const pct=Math.max(0,a.t/a.m*100);let ic;if(a.k==='magnet')ic='<path d="M6 4v6a6 6 0 0012 0V4" fill="none" stroke="#e0453a" stroke-width="3"/>';else if(a.k==='shield')ic='<path d="M12 3l7 3v5c0 4-3 7-7 9-4-2-7-5-7-9V6z" fill="#5aa0e0"/>';else if(a.k==='rocket')ic='<path d="M12 2c3 3 4 7 4 10l-2 3h-4l-2-3c0-3 1-7 4-10z" fill="#e0453a"/>';else if(a.k==='bolt')ic='<path d="M13 2L4 14h6l-1 8 9-12h-6z" fill="#ffd23f"/>';else ic='<text x="12" y="17" font-size="12" font-weight="700" text-anchor="middle" fill="#ffd23f" font-family="Fredoka">2×</text>';return '<div class="pw"><div class="fill" style="height:'+pct+'%;background:'+a.c+'"></div><svg viewBox="0 0 24 24">'+ic+'</svg></div>';}).join('');}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.style.transition='none';el.style.opacity='1';el.style.transform='translateX(-50%) scale(1.2)';requestAnimationFrame(()=>{el.style.transition='opacity .8s,transform .8s cubic-bezier(.16,1,.3,1)';el.style.opacity='0';el.style.transform='translateX(-50%) scale(1) translateY(-30px)';});}
let AC=null;
function beep(f,d){if(!S.sound)return;try{AC=AC||new(window.AudioContext||window.webkitAudioContext)();const o=AC.createOscillator(),g=AC.createGain();o.frequency.value=f;o.type='square';g.gain.value=0.05;o.connect(g);g.connect(AC.destination);o.start();g.gain.exponentialRampToValueAtTime(0.001,AC.currentTime+d);o.stop(AC.currentTime+d);}catch(e){}}
function vibrate(ms){if(S.vibe&&navigator.vibrate)navigator.vibrate(ms);}
const screens=['menu','shop','skills','settings','game','pause','gameover'];
function showScreen(id){screens.forEach(s=>document.getElementById(s).classList.add('hidden'));document.getElementById(id).classList.remove('hidden');if(id==='menu'){refreshMenu();mode='menu';}}
function refreshMenu(){document.getElementById('m-coins').textContent=S.coins.toLocaleString();document.getElementById('m-gems').textContent=S.gems.toLocaleString();}
document.getElementById('btn-play').onclick=startRun;
document.getElementById('btn-shop').onclick=()=>{showScreen('shop');buildShop();};
document.getElementById('btn-skills').onclick=()=>{showScreen('skills');buildSkills();};
document.getElementById('btn-settings').onclick=()=>{showScreen('settings');buildSettings();};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>showScreen('menu'));
document.getElementById('pausebtn').onclick=()=>{if(mode==='play'){mode='pause';document.getElementById('pause').classList.remove('hidden');}};
document.getElementById('resume').onclick=()=>{document.getElementById('pause').classList.add('hidden');mode='play';};
document.getElementById('pause-home').onclick=()=>showScreen('menu');
document.getElementById('retry').onclick=startRun;
document.getElementById('go-home').onclick=()=>showScreen('menu');
function buildShop(){document.getElementById('s-coins').textContent=S.coins.toLocaleString();document.getElementById('s-gems').textContent=S.gems.toLocaleString();const grid=document.getElementById('charGrid');grid.innerHTML='';Object.keys(CHARS).forEach(id=>{const c=CHARS[id],owned=S.owned[id],sel=S.selected===id,isGem=!!c.cost.g,price=isGem?c.cost.g:c.cost.c;const wrap=document.createElement('div');wrap.className='char'+(sel?' sel':'')+(!owned?' locked':'');const priceHtml=owned?'':'<div class="price">'+(isGem?'<svg class="ic" viewBox="0 0 24 24"><path d="M4 9l3-4h10l3 4-8 11z" fill="#e0453a"/></svg>':'<svg class="ic" viewBox="0 0 24 24"><circle cx="12" cy="12" r="11" fill="#e9a324"/><circle cx="12" cy="12" r="7.5" fill="#f7c948"/></svg>')+price.toLocaleString()+'</div>';let btn;if(sel)btn='<button class="cbtn sel">SELECTED</button>';else if(owned)btn='<button class="cbtn buy" data-select="'+id+'">SELECT</button>';else{const afford=isGem?S.gems>=price:S.coins>=price;btn=afford?'<button class="cbtn buy" data-buy="'+id+'">BUY</button>':'<button class="cbtn need" disabled>'+(isGem?'GEMS NEEDED':'NEED COINS')+'</button>';}wrap.innerHTML='<canvas width="150" height="96"></canvas>'+(!owned?'<svg class="lockbadge" viewBox="0 0 24 24"><rect x="5" y="10" width="14" height="10" rx="2" fill="#cfd4dc"/><path d="M8 10V7a4 4 0 018 0v3" fill="none" stroke="#cfd4dc" stroke-width="2.5"/></svg>':'')+'<div class="cname">'+c.name+'</div>'+priceHtml+btn;grid.appendChild(wrap);drawPortrait(wrap.querySelector('canvas').getContext('2d'),75,88,1.15,1.2,id);});grid.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buyChar(b.dataset.buy));grid.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{S.selected=b.dataset.select;save();buildShop();});}
function buyChar(id){const c=CHARS[id],isGem=!!c.cost.g,price=isGem?c.cost.g:c.cost.c;if(isGem){if(S.gems<price)return;S.gems-=price;}else{if(S.coins<price)return;S.coins-=price;}S.owned[id]=true;S.selected=id;save();beep(900,0.1);buildShop();refreshMenu();}
function buildSkills(){const list=document.getElementById('skillList');list.innerHTML='';const icons={magnet:'<path d="M6 4v7a6 6 0 0012 0V4h-4v7a2 2 0 01-4 0V4z" fill="#e0453a"/>',shield:'<path d="M13 3l8 3v6c0 5-3.5 8-8 10-4.5-2-8-5-8-10V6z" fill="#5aa0e0"/><path d="M13 8l1.5 3H18l-2.5 2 1 3.5-3.5-2-3.5 2 1-3.5L8 11h3.5z" fill="#fff"/>',boost:'<path d="M13 2c4 4 5 9 5 12l-3 4h-4l-3-4c0-3 1-8 5-12z" fill="#e0453a"/><circle cx="13" cy="9" r="2.5" fill="#5aa0e0"/>',multiplier:'<path d="M13 2l3 6 6 1-4 5 1 6-6-3-6 3 1-6-4-5 6-1z" fill="#ffd23f"/><text x="13" y="16" font-size="8" font-weight="700" text-anchor="middle" fill="#8a5a00" font-family="Fredoka">2×</text>'};Object.keys(SKILL_DEFS).forEach(id=>{const d=SKILL_DEFS[id],lvl=S.skills[id],maxed=lvl>=d.max,cost=d.base*(lvl+1);const dots=Array.from({length:d.max},(_,i)=>'<div class="dot'+(i<lvl?' on':'')+'"></div>').join('');const row=document.createElement('div');row.className='skill-row';row.innerHTML='<svg class="sk-ic" viewBox="0 0 26 26">'+icons[id]+'</svg><div class="sk-body"><div class="sk-name">'+d.name+'</div><div class="sk-desc">'+d.desc+'</div><div class="dots">'+dots+'</div></div>'+(maxed?'<button class="upg max" disabled>MAX</button>':'<button class="upg" data-up="'+id+'"><div style="font-size:11px;opacity:.9">UPGRADE</div><div style="display:flex;align-items:center;gap:3px;justify-content:center"><svg width="14" height="14" viewBox="0 0 24 24"><circle cx="12" cy="12" r="11" fill="#fff" opacity=".9"/><circle cx="12" cy="12" r="7" fill="#e9a324"/></svg>'+cost.toLocaleString()+'</div></button>');list.appendChild(row);});list.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const id=b.dataset.up,d=SKILL_DEFS[id],cost=d.base*(S.skills[id]+1);if(S.coins>=cost&&S.skills[id]<d.max){S.coins-=cost;S.skills[id]++;save();beep(1000,0.1);buildSkills();refreshMenu();}else beep(250,0.15);});}
function buildSettings(){document.getElementById('sw-sound').classList.toggle('on',S.sound);document.getElementById('sw-music').classList.toggle('on',S.music);document.getElementById('sw-vibe').classList.toggle('on',S.vibe);}
document.getElementById('sw-sound').onclick=e=>{S.sound=!S.sound;e.target.classList.toggle('on',S.sound);save();beep(600,0.05);};
document.getElementById('sw-music').onclick=e=>{S.music=!S.music;e.target.classList.toggle('on',S.music);save();};
document.getElementById('sw-vibe').onclick=e=>{S.vibe=!S.vibe;e.target.classList.toggle('on',S.vibe);save();vibrate(60);};
document.getElementById('reset-row').onclick=()=>{if(confirm('Wipe all progress?')){S=JSON.parse(JSON.stringify(defaults));S.coins=0;S.gems=0;S.best=0;S.owned=baseOwned();S.selected='hero';S.skills={magnet:0,shield:0,boost:0,multiplier:0};save();buildSettings();refreshMenu();}};
document.getElementById('d-up').onclick=jump;
document.getElementById('d-down').onclick=slide;
document.getElementById('d-left').onclick=()=>moveLane(-1);
document.getElementById('d-right').onclick=()=>moveLane(1);
let hintHidden=false;
function hideHint(){if(!hintHidden){hintHidden=true;const h=document.getElementById('hint');if(h)h.style.opacity='0';}}
let tsx=null,tsy=null,tt=0;
cv.addEventListener('pointerdown',e=>{tsx=e.clientX;tsy=e.clientY;tt=performance.now();});
cv.addEventListener('pointerup',e=>{if(tsx===null)return;const dx=e.clientX-tsx,dy=e.clientY-tsy;hideHint();if(Math.abs(dx)>36&&Math.abs(dx)>Math.abs(dy)){moveLane(dx>0?1:-1);}else if(dy<-36&&Math.abs(dy)>Math.abs(dx)){jump();}else if(dy>36&&Math.abs(dy)>Math.abs(dx)){slide();}else if(performance.now()-tt<300){jump();}tsx=null;});
window.addEventListener('keydown',e=>{hideHint();if(['ArrowUp','Space','KeyW'].includes(e.code)){e.preventDefault();jump();}else if(['ArrowDown','KeyS'].includes(e.code)){e.preventDefault();slide();}else if(['ArrowLeft','KeyA'].includes(e.code)){e.preventDefault();moveLane(-1);}else if(['ArrowRight','KeyD'].includes(e.code)){e.preventDefault();moveLane(1);}else if(e.code==='Escape'&&mode==='play')document.getElementById('pausebtn').click();});
refreshMenu();renderHearts(3);
